### ISSUE TITLE
Handling DatePicker.js

### ISSUE THREAD

**Issue by aalqah13** [KASHO7/project3#2]
As a team member, I want to create a JavaScript file to handle the functionality of the DatePicker component, so that I can ensure the DatePicker meets the following interactive requirements:

1. Display a grid calendar for the selected month.
2. Include a header row with day abbreviations.
3. Highlight days of the current month; dim others.
4. Adjust the calendar height dynamically.
5. Show the current month and year.
6. Add clickable navigation controls ("<" and ">").
7. Invoke a callback on valid day clicks.

By completing this user story, I will have a DatePicker.js file that provides the necessary functionality for the DatePicker component.

**Comment by KASHO7** [comment]
datepicker.js is now working, ready for code review

**Comment by aalqah13** [comment]
Thank you for the feedback.
