### ISSUE TITLE
Handling DatePicker.css

### ISSUE THREAD

**Issue by aalqah13** [KASHO7/project3#3]
As a team member, I want to create a CSS file, so that I can style the DatePicker component according to the following requirements:

1. Style the calendar grid and spacing.
2. Design the header row with clear day abbreviations.
3. Style the month and year display.
4. Navigation control visuals ("<" and ">").
5. Provide an appealing user experience.

By completing this user story, I will have a DatePicker.css file that provides the necessary styling for the DatePicker component.

**Comment by 1melkey33** [comment]
file is ready for a code review and testing

**Comment by aalqah13** [comment]
Thank you for the feedback.
