### ISSUE TITLE
Handling TableTemplate.js

### ISSUE THREAD

**Issue by aalqah13** [KASHO7/project3#4]
As a team member, I want to create a JavaScript file, So that I can implement a TableTemplate class with a fillIn static method that dynamically populates HTML tables with data from a dictionary object while respecting specified column names.

1. fillIn takes three arguments: table id, a dictionary object, and a string columnName.
2. When columnName is specified, fill in {{property}} elements in that column with dictionary values; return if the column doesn't exist.
3. Assume the first row of the table has unique column names.
4. If no columnName is provided, process the entire table.
5. Replace templates with empty strings if the dictionary lacks the specified property.

By implementing this user story, we will have a TableTemplate.js file that contains a **TableTemplate** class with a **fillIn** method.

**Comment by JChilds1012** [comment]
the file is ready to be tested

**Comment by aalqah13** [comment]
Thank you for the feedback.
